#!/usr/bin/env python3
"""Regenerate tests/fixtures/golden.{json,ts} from the Python core (the reference implementation).

Run after any intentional change to pruning or hashing, then review the diff. The TypeScript core
tests and the Python drift test both read these files, so the two cores cannot silently diverge.
"""
import json
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from jevkit import core  # noqa: E402

DIGEST_INPUTS = ['session-golden', '/work/project', '/tmp/données 日本語"quote']


def build():
    cases = []

    def case(name, text):
        output, meta = core.prune(text, 'rules')
        cases.append({'name': name, 'input': text, 'expected_output': output,
                      'expected_input_chars': meta['input_chars'], 'expected_reason': meta['reason']})

    lines = [f'progress item {i}\n' for i in range(320)]
    lines[141] = 'ERROR build: expected contract 1, got invalid\n'
    case('long-with-error', ''.join(lines))
    case('crlf-and-unicode',
         ''.join(f'步驟 {i} ok\r\n' for i in range(100))
         + 'Traceback (most recent call last):\r\n  File "x.py", line 1\r\nValueError: 壞了\r\n'
         + ''.join(f'步驟 {i} ok\r\n' for i in range(100, 200)))
    case('separators', 'a\x0bb\x0cc\x1cd\x85e f g\n' * 40)
    case('no-trailing-newline', ''.join(f'line {i}\n' for i in range(80)) + 'last line without newline FAIL')
    case('all-important', ''.join(f'error {i}\n' for i in range(50)))
    filler = lambda n: [f'filler {i}\n' for i in range(n)]
    for name, special in [('cr-in-at-line', 'at foo\rbar:12\n'), ('unicode-digit', 'at foo:\u0663\n'),
                          ('dotless-i', 'FA\u0131L\n'), ('x1f-file', '\x1f File x\n'), ('unicode-word-boundary', 'warn\u00e9 x\n'),
                          ('emoji-lines', '\U0001F600 emoji line ERROR\n')]:
        case(name, ''.join(filler(40)) + special + ''.join(filler(40)))
    warn = lambda n, tag='deprecated api': [f'WARNING: {tag} call #{i} at step {i * 7}\n' for i in range(n)]
    case('repeated-warnings', ''.join(filler(30)) + ''.join(warn(200)) + ''.join(filler(30)))
    case('warnings-below-threshold', ''.join(filler(30)) + ''.join(warn(5)) + ''.join(filler(30)))
    case('warnings-with-error-never-collapsed', ''.join(filler(30)) + ''.join(warn(100, 'warn error code')) + ''.join(filler(30)))
    case('warning-runs-broken-by-error', ''.join(filler(30)) + ''.join(warn(10)) + 'ERROR boom\n' + ''.join(warn(10)) + ''.join(filler(30)))
    case('warning-run-no-trailing-newline', ''.join(filler(30)) + ''.join(warn(9))[:-1])
    case('emoji-bulk', ''.join(f'\U0001F600 line {i}\n' for i in range(120)))
    redactions = [{'input': t, 'expected': core.redact(t)} for t in [
        'Authorization: Bearer abcdefSECRET123',
        '{"api_key": "SECRETJSON123", "password":"PW99"}',
        'password: "quoted secret"',
        "token='single quoted value' next",
        'curl -H "Authorization: Basic dXNlcjpwYXNz1234" url',
        'sk-abcdefghijklmnop and ghp_abcdefghijklmnop and AKIAABCDEFGHIJKLMNOP',
        'plain text with no secrets: tokenizer is fine',
    ]]
    option_env = {'mode': 'MODE', 'backend': 'BACKEND', 'minimum_chars': 'MINIMUM_CHARS',
                  'keep_threshold': 'KEEP_THRESHOLD', 'retention_days': 'RETENTION_DAYS', 'enable_all_projects': 'ENABLE_ALL_PROJECTS'}
    merge_inputs = [
        ({}, None), ({'mode': 'assist'}, None), ({'enable_all_projects': True}, None),
        ({'mode': 'assist', 'backend': 'jev'}, {'mode': 'observe'}),
        ({'mode': 'bogus', 'minimum_chars': 5000}, None), ({'minimum_chars': 999999999}, None),
        ({'keep_threshold': 0.5, 'retention_days': 14}, {'enabled': True}),
        ({'enable_all_projects': True}, {'enabled': False}), ({}, {'endpoint': 'https://evil.example'}),
        ({'retention_days': 0}, {'minimumChars': 100}),
    ]
    merges = []
    for options, project in merge_inputs:
        env = {'CLAUDE_PLUGIN_OPTION_' + option_env[k]: str(v).lower() if isinstance(v, bool) else str(v) for k, v in options.items()}
        with tempfile.TemporaryDirectory() as td:
            if project is not None:
                (Path(td) / '.claude').mkdir()
                (Path(td) / '.claude' / 'jev-agent-kit.json').write_text(json.dumps(project))
            try:
                expected = core.config(td, env)
            except ValueError as exc:
                expected = {'error': str(exc)}
        merges.append({'options': options, 'project': project, 'expected': expected})
    return {'merges': merges, 'redactions': redactions, 'digests': {v: core.digest(v)[:24] for v in DIGEST_INPUTS}, 'cases': cases}


def render():
    gold = build()
    as_json = json.dumps(gold, ensure_ascii=False, indent=1) + '\n'
    as_ts = '// Generated by scripts/gen_golden.py. Do not edit.\nexport default ' + as_json
    return as_json, as_ts


if __name__ == '__main__':
    as_json, as_ts = render()
    (ROOT / 'tests' / 'fixtures' / 'golden.json').write_text(as_json, encoding='utf-8')
    (ROOT / 'tests' / 'fixtures' / 'golden.ts').write_text(as_ts, encoding='utf-8')
    print('wrote tests/fixtures/golden.json and golden.ts')
